# Generated by Django 5.2.18 on 2026-10-10 10:01

import django.core.validators
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(blank=True, upload_to=catalog.models.category_photo_path),
        ),
        migrations.AddField(
            model_name="category",
            name="photo_x",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="photo_y",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="photo_zoom",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="100 to 200 percent.",
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
