# Generated by Django 5.2.18 on 2026-10-10 17:56

from django.db import migrations, models


def mark_existing_parents(apps, schema_editor):
    category = apps.get_model("catalog", "Category")
    categories = category.objects.using(schema_editor.connection.alias)
    parent_ids = categories.exclude(parent_id=None).values("parent_id")
    categories.filter(pk__in=parent_ids).update(is_parent_category=True)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_photo_category_photo_x_category_photo_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_parent_category",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(mark_existing_parents, migrations.RunPython.noop),
    ]
